### ISSUE TITLE
PHP 8?

### ISSUE THREAD

**Issue by stanimirdim92** [kafkiansky/service-locator-interrupter#3]
I'm configuring psalm and I think that this plugin is awesome. Can you fix composer to allow php8 and laravel 8?

Running ```composer require kafkiansky/service-locator-interrupter --dev``` outputs:

```
[InvalidArgumentException]                                                                                                                    
  Package kafkiansky/service-locator-interrupter has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version 
```

Running Laravel 8.19, PHP 7.4 in apache and PHP 8 on cli with composer 2.

**Comment by kafkiansky** [comment]
Hi, @stanimirdim92, thank you for issue. Done: https://github.com/kafkiansky/service-locator-interrupter/releases/tag/v2.0.0

**Comment by stanimirdim92** [comment]
Got an exception. Using psalm without the plugin works fine.

```
Uncaught Exception: ReflectionClass::__construct(): Argument #1 ($objectOrClass) must be of type object|string, null given
Stack trace in the forked worker:
#0 /var/www/html/nettoffice-api/vendor/kafkiansky/service-locator-interrupter/src/Hooks/PreventContainerUsage.php(115): ReflectionClass->__construct()
#1 /var/www/html/nettoffice-api/vendor/kafkiansky/service-locator-interrupter/src/Hooks/PreventContainerUsage.php(60): Kafkiansky\ServiceLocatorInterrupter\Hooks\PreventContainerUsage::isServiceLocatorCall()
#2 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(980): Kafkiansky\ServiceLocatorInterrupter\Hooks\PreventContainerUsage::afterStatementAnalysis()
#3 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1978): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()
#4 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1388): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#5 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(850): Psalm\Internal\Analyzer\ClassAnalyzer->checkPropertyInitialization()
#6 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(211): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#7 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#8 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#9 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(406): Psalm\Internal\Fork\Pool->__construct()
#10 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#11 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#12 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#13 /var/www/html/nettoffice-api/vendor/vimeo/psalm/psalm(2): require_once('...')
#14 {main} in /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(473): Psalm\Internal\Fork\Pool->wait()
#2 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#3 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#4 /var/www/html/nettoffice-api/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#5 /var/www/html/nettoffice-api/vendor/vimeo/psalm/psalm(2): require_once('...')
#6 {main}
(Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476 crashed due to an uncaught Throwable)
```

**Comment by kafkiansky** [comment]
@stanimirdim92, my mistake, sorry. update to 2.0.1 and check now, please

**Comment by stanimirdim92** [comment]
Everything works fine. Now I need to fix that 5k errors :D
